config/routes.rb
Rails.application.routes.draw do
  # get 'lists/new'
  # get 'bookmarks/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :movie_id, scope: [:list_id]
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = @list.id
    @bookmark.movie_id = @movie.id
    if @bookmark.save
      redirect_to lists_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:list_id])
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])

    @bookmarks = Bookmark.where(list_id: @list.id)
    # @bookmark.movie_id
    @movies = []
    @bookmarks.each do |bookmark|
      movie_id = bookmark.movie_id
      @movies << Movie.find(movie_id)
    end
    @bookmark = Bookmark.find(params[:movie_id])
    # movies.each do |movie|
    #   @movies = Movie.find(movie)
    # end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmarks</h1>
<p>Create a bookmark here YO!</p>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Here are your lists</h1>

<% @lists.each do |list| %>
  <div><%= link_to list.name, list_path(list) %></div>
<% end %>

app/views/lists/new.html.erb
<h1>Lists</h1>
<p>You can add your new list here</p>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>This is your <%= @list.name %> page</h1>


<% @movies.each do |movie| %>
  <div><%=movie.title%><%=link_to "Delete", bookmark_path(@bookmark)%></div>
<% end %>

<%=link_to "Create a bookmark", new_list_bookmark_path(@list) %>